#!/usr/bin/bash
# AWS S3 backup removal.
# Delete folders older than 3 days.
source ./functions/output

bucket="s3://bucket/"
firstparty=($(aws s3 ls ${bucket}folder/ | awk '{print $2}' | grep -Po '\d{8}'))
deleteday=$(date -d '-3 days' +%Y%m%d)
log="/var/log/LOG"

delete_folder(){
  aws s3 rm ${bucket}folder/$1/ --recursive
  find $log -iname "$1*" -exec rm -rf {} \;
}

main(){
  for folder in "${firstparty[@]}"; do
    if [[ $folder -lt $deleteday ]]; then
     delete_folder ${folder}
     slack_notification "Backup $folder has been deleted!"
    fi
  done
}

main "$@"
