#!/usr/bin/bash
# Disk Usage check
device=$1

usage(){
  echo "Usage: $0 device"
  exit 1
}

main(){
  if [[ $# -ne 1 ]] || [[ -z $device ]]; then
    usage
  else 
    disk_usage=$(df -P /home 2>/dev/null | grep -oP '\d{1,2}(?=%)')
    
    if [[ $disk_usage -gt 90 ]]; then
      echo "CRITICAL- $device usage is above 90%" 
      exit 2
    else 
      echo "OK- $device usage is below 90%"
      exit 0
    fi
  fi
}

main "$@"
