#!/usr/bin/bash
# HTTP CHECK.
# USAGE: url_validator FILE
# FILE: could contain one or more urls separated by new lines.
source PATH/functions/slack_notification
declare -a urls
file=PATH

url_validation(){
  response=$(curl -k -X GET -s -o /dev/null -w '%{http_code}\n' "$1")
  if [[ ! $response =~ (200|301|302) ]]; then
    urls+=($(printf '%s\n' "$1"))
  fi
}

main(){

  while read url; do
    url_validation $url
  done < $file
  
  to_slack=$(printf "%s\n"  "${urls[@]}")

  if [[ ! -z $to_slack ]]; then
    slack_notification_1p "\`\`\`Unreachable URLs:\n$to_slack\`\`\`"
  fi
}

main "$@"
