#!/usr/bin/bash
# Green Arrow sent stats by today.
source ./functions/slack-webhook

main(){
  main_query=$(cat <<EOF 
    select b.listid, 
           coalesce((total_messages), 0) as "Total Sent",
           coalesce((total_messages - total_success - total_failure),0) as "Total inqueue"
    from   sends a, sends_lists b
    where  sendid not like ('%_-ic')
    and    a.id = b.send_id
    and    injtime_first > extract(epoch from (Now() - interval '1' day))
    and    (total_messages - total_success - total_failure) > 100
    order by 3 desc
EOF
)
  data=$(psql -c "$main_query")
  slack_notification "\`\`\`$data\`\`\`"  
}

main "$@"
