#!/usr/bin/bash
# Nagios ip tunnel checker.
# Can be used with parallel.

start_ip=$1
end_ip=$2
subnet=${start_ip%.*}
failed=""
down=0

usage(){
  echo "WARNING- Arguments failed!"
  exit 1
}

check_ip(){
  #change ping to desired approach.
  ping -c1 -W1 -I $1 domain.com >/dev/null 2>&1
  
  if [[ $? -eq 0 ]]; then
    continue
  else
    down=$((down+1))
    failedips+="$1 "
  fi
}

# uncomment to use xargs:
#export -f check_ip

main(){
  if [[ $# -ne 2 ]]; then
    usage
  else 
    for i in $(seq ${start_ip##*.} ${end_ip##*.}); do
      # parallel ping:
      # printf $subnet.$i | xargs -n 1 -P4 -I{} bash -c 'check_ip "$@"' \;
      check_ip $subnet.$i
    done

    if [[ $down -eq 0 ]]; then
      echo "PORT 25 OK: $start_ip is responding."
      exit 0
    else 
      echo "WARNING- $failedips"
      exit 2
    fi
  fi
}

main "$@"
