#!/usr/bin/bash
# Waterfall script. 
# Adding iptable rules as requested:
portnumber=$1
source ./functions/output

if [[ $# -ne 1 ]]; then
  echo "$0 portnumber"
  exit 1
fi

# Stopping firewalld.
echo "Stopping firewalld:"
systemctl stop firewalld
output $? "Stopping firewalld"

#Masking firewalld.
echo "Masking firewalld:"
systemctl mask firewalld
output $? "Masking firewalld"

# installing packages:
echo "Installing dependencies:"
yum install iptables-services -q -y
output $? "Installing iptables"

# Enabling iptables service.
echo "Enabling iptables service:"
systemctl enable iptables
output $? "Enabling iptables"

# Adding rules to iptables:
echo "Adding rules to iptables: "
cat << EOF >> /etc/sysconfig/iptables
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22022 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 25 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 110 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 4500 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 465 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5666 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
EOF

# Restarting service:
echo "Restarting iptables service:"
systemctl restart iptables
output $? "Restarting iptables"

iptables -L -n

echo "Setting ssh port to specified: "
yum install -y -q policycoreutils-python
output $? "Installing policycoreutils"

semanage port -a -t ssh_port_t -p tcp $portnumber
output $? "Restarting sshd"

sed -i "s/\#Port\ 22/Port $portnumber/g" /etc/ssh/sshd_config 

systemctl restart sshd 
output $? "Restarting sshd"
