#!/bin/bash
# User add script.
source /functions/output

usage(){
  echo "$0 username password"
  exit 1
}

add(){
  if [[ $# -ne 2 ]] || [[ -z $1 ]] || [[ -z $2 ]];then 
    usage
  else 
    user=$1
    pass=$2
  
    echo "Creating user: $user"
    useradd -m $user
    echo $pass | passwd $user --stdin
    usermod -aG wheel $user
    output $? "Set password"
  
    mkdir /home/$user/.ssh/
    ssh user@server "cat /home/$user/.ssh/authorized_keys" > /home/$user/.ssh/authorized_keys
    output $? "Adding ssh key"
  
    chmod 700 /home/$user/.ssh
    chmod 600 /home/$user/.ssh/authorized_keys

    chown $user:$user /home/$user/.ssh
    chown $user:$user /home/$user/.ssh/authorized_keys
    output $? "User creation"
  fi
}


main(){
  add $1 $2
}

main "$@"
