#!/usr/bin/python
# Add Domain to greenarrow:
import requests, json, sys
from requests.auth import HTTPBasicAuth
requests.packages.urllib3.disable_warnings()

user='user'
password='password'

try:
  sys.argv[1]
except IndexError:
  print "Usage: " + sys.argv[0] + " domain.com"
  exit(1)

def create_domain():
  endpoint = "https://URL/ga/api/v3/eng/incoming_email_domains"
  data = json.dumps({
  "domain": {
  "domain": sys.argv[1],
  "email_status": "normal" }
  })
  
  try:
    response = requests.post(endpoint, data, auth=(user, password))
    if response == 200:
      return "Domain has been added succesfully."
  except requests.ConnectionError:
    return "Failed to connect, try again."
  
# call the function huh?
