#!/usr/bin/python	
import requests, json	
from requests.auth import HTTPBasicAuth	
requests.packages.urllib3.disable_warnings()	

def get_domain_id(domain):	
    endpoint = 'https://URL/ga/api/v3/eng/incoming_email_domains'	
    response = requests.get(endpoint, auth=(user, password))	
    data = json.loads(response.text)['data']['domains']	

    for i in data:	
        if i['domain'] == 'hostname':	
            return i['id']	

def get_id(mailclass):	
    endpoint = 'https://hostname/ga/api/v3/eng/ip_addresses'	
    response = requests.get(endpoint, auth=(user, password))	
    data = json.loads(response.text)['data']['ip_addresses']	

    for i in data:	
        if i['name'] == mailclass: 	
            return i['id']	

